image: node:16.14.0
pipelines:
  pull-requests:
    '**': # This runs as default for any branch not elsewhere defined
      - step:
          name: "Verify Dependencies, Formatting, Typechecking, Linting and Tests"
          caches:
            - node
          script:
            - yarn install --frozen-lockfile
            - yarn check-format
            - yarn type-check
            - yarn lint
            - yarn test
  branches:
    main:
      - step:
          name: "Verify Dependencies, Formatting, Typechecking, Linting and Tests"
          caches:
            - node
          script:
            - yarn install --frozen-lockfile
            - yarn check-format
            - yarn type-check
            - yarn lint
            - yarn test
  custom: # Pipelines that can only be triggered manually or by a schedule
    qa-nightly-build:
      - step:
          name: "Trigger nightly build"
          caches:
            - node
          script:
            - bash ./scripts/qa-nightly-build.sh
