export const IS_BIOMETRIC_ENABLED = 'IS_BIOMETRIC_ENABLED';
export const IS_PASSCODE_ENABLED = 'IS_PASSCODE_ENABLED';
export const AVAILABLE_BIO_KEY = 'AVAILABLE_BIO_KEY';
export const BIO_STORAGE_KEY = 'BIO_STORAGE_KEY';
export const LAST_ACTIVE_KEY = 'LAST_ACTIVE_KEY';
export const IS_AUTHED = 'IS_AUTHED';
